### PR TITLE
leveling: improve leaderboard display

### LINKED ISSUE #230: request: leveling: remove members who left the server
**Describe the bug in as much detail as possible:**

When running the `!lb` command, it still shows the xp and levels of thoes who left the server!

**To Reproduce:**

1. Have someone leave your server who **has xp**
2. Run `!lb`
3. See blank name 

**Expected behavior:**
For members who left to automatically be removed from the leaderboard and to not come up with blank names 

**Screenshots:**
Leaderboard
(I set my prefix to `!`)

### PR DESCRIPTION
**Pull request by l-zeuch**
This commit improves the leaderboard of the levelling system to show the
ID instead of a blank #, should they have left the server.

Closes #230

Signed-off-by: Luca Zeuch <l-zeuch@email.de>

**Status**

- [x] Code changes have been tested on an instance of YAGPDB, or there are no code changes
- [x] I have read and followed the [contribution guide](https://github.com/yagpdb-cc/yagpdb-cc/blob/master/CONTRIBUTING.md)
- [x] I have [written documentation](https://github.com/yagpdb-cc/yagpdb-cc/blob/master/WRITING-DOCUMENTATION.md) for my changes, or there is no need to

### CODE REVIEW

File: src/leveling/leaderboard.go.tmpl [hunk 1]
```diff
@@ -15,10 +15,11 @@
 	{{ $rank := $skip }}
 	{{ $display := "" }}
 	{{ range $users }}
+	        {{- $usr := or ( and (ne .User.String "#") .User.String ) .UserID }}
```
Comment (jo3-l) [inline src/leveling/leaderboard.go.tmpl:18]: Please use a branch for this. (As is, it's mildly unreadable at a glance.)
Also, tabs instead of spaces for consistency with the rest of the file. Thanks.

**Review by jo3-l — CHANGES_REQUESTED** [review]

**Review by jo3-l — APPROVED** [review]
LGTM

**Comment by l-zeuch** [comment]
Let's :shipit:
